AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true

#
# Metrics
#

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 100

Metrics/LineLength:
  Max: 128

Metrics/MethodLength:
  Max: 25

#
# Style
#

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
