language: ruby
cache: bundler

before_install:
  - gem update --system
  - gem --version
  - gem install bundler -v 1.16.1
  - bundle --version

rvm:
  - 2.2
  - 2.3
  - 2.4.3
  - 2.5.0

matrix:
  fast_finish: true

branches:
  only:
    - master
